### ISSUE TITLE
ACA some changes not working

### ISSUE THREAD

**Issue by SanjayBandhniya** [Alfresco/alfresco-docker-installer#170]
I am using this application for my alfresco and alfresco content app.
I have cloned https://github.com/Alfresco/alfresco-content-app and made some changes like login page,theme change and add new column in documentlibrary.
Now I am deploying these code(build) using below way.content-ce is the folder where generated build is there.

```
 content-app:
        image: alfresco/alfresco-content-app:${ACA_TAG}
        mem_limit: 256m
        environment:
            APP_BASE_SHARE_URL: "http://${SERVER_NAME}:80/#/preview/s"
        depends_on:
            - alfresco
        volumes:
            - ./content-ce:/usr/share/nginx/html
```
 

Login page and theme changes are working but documentlibrary added column not showing.
Separately I tried to deploy these changes in independent tomcat to verify then working fine but docker way not working.
