### ISSUE TITLE
[Proposal] Healthcheck for ACS on docker-compose

### ISSUE THREAD

**Issue by iohann95** [Alfresco/alfresco-docker-installer#219]
Good afternoon everyone.
Alfresco already has an endpoint to verify if the application is running ok:

```yaml
        healthcheck:
          test: "curl -f http://localhost:8080/alfresco/api/-default-/public/alfresco/versions/1/probes/-live-"
          interval: 30s
          timeout: 10s
          retries: 6
          start_period: 10m
```

On my personal opinion it would be good as this helped me to keep track of the status of my Alfresco instances on my Zabbix.
If the project maintainers agree I can do a pull request.
Thanks.
