### ISSUE TITLE
remove postgres from yml file and setup connection to an existing postgres database

### ISSUE THREAD

**Issue by paynent** [Alfresco/alfresco-docker-installer#64]
Is there any way to modify the docker-compose.yml file that we can find on the website to accomplish this?

**Comment by aborroy** [comment]
Remove the following service from generated `docker-compose.yml` file.

```
    postgres:
        image: postgres:${POSTGRES_TAG}
        mem_limit: 848m
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: "
            postgres
              -c max_connections=200
              -c logging_collector=on
              -c log_min_messages=LOG
              -c log_directory=/var/log/postgresql"
        ports:
            - 5432:5432
        volumes: 
            - ./data/postgres-data:/var/lib/postgresql/data
            - ./logs/postgres:/var/log/postgresql 
```

Change connection properties in `alfresco` service from generated `docker-compose.yml` file.

```
    alfresco:
        environment:
            JAVA_OPTS : '
                -Ddb.username=<YOUR_USERNAME>
                -Ddb.password=<YOUR_USERPASSWORD>
                -Ddb.url=jdbc:postgresql://<YOUR_DB_HOSTNAME>:5432/alfresco  
```
