### ISSUE TITLE
Disable Alfresco Content App or Redirect to Alfresco Share only?

### ISSUE THREAD

**Issue by infinite-dao** [Alfresco/alfresco-docker-installer#76]
Hej-hej,

is there a way to disable the Alfresco Content App on, say `https://my-special-server.org` and only have Alfresco Share up and running on `https://my-special-server.org/share/`  ? 

I tried to remove (or commented out) in `docker-compose.yml` all definitions relating to `alfresco/alfresco-content-app …` but then the whole Alfresco Share did not work.

Or are there related configuration variables to achieve this?

Thank you for your suggestions on this issue

**Comment by luiscolorado** [comment]
Share is just an Alfresco user interface, so Alfresco should not be disabled, or Share will not work.

**Comment by aborroy** [comment]
@luiscolorado I guess @infinite-dao is talking about ACA (the ADF UI).

You need also to disable that application from the "proxy" service: https://github.com/aborroy/acs-proxy

Add ACA_ENABLED=false in the proxy environment section.

**Comment by infinite-dao** [comment]
> Add ACA_ENABLED=false in the proxy environment section.

Ah yes, this does this; although the `https://my-special-server.org/` is now returning default 404 error page. 

Is there an easy direct way to implement a nginx-redirect that stays permanent in place over any docker-compose rebuilts ? 

I guess, from reading https://github.com/aborroy/acs-proxy `entrypoint.sh` and stuff, then I only can achieve it on docker level or docker-compose level somehow … but I’m not really familiar with this.

**Comment by aborroy** [comment]
You can use default NGINX proxy Docker Image with your own configuration file:

https://github.com/Alfresco/alfresco-docker-installer/blob/57b2e5b07b533d46bf2381683d03d720268b88d5/generators/app/templates/images/config/nginx/nginx.conf

Just mount it as an external volume:
https://github.com/Alfresco/alfresco-docker-installer/blob/57b2e5b07b533d46bf2381683d03d720268b88d5/generators/app/templates/6.2/docker-compose.yml#L247

**Comment by infinite-dao** [comment]
> You can use default NGINX proxy Docker Image with your own configuration file

I got it running with the following proxy, simplfied `docker-compose.yml` to show only my changes:
```yml
services:
    alfresco:        
        # ... cut out, use default or modified
    transform-core-aio:
        # ... cut out , use default or modified
    share:
        # ... cut out , use default or modified
    postgres:
        # ... cut out , use default or modified
    solr6:
        # ... cut out , use default or modified
    activemq:
        # ... cut out , use default or modified
    content-app:
        # ... cut out , use default or modified
    proxy:
        image: nginx:stable-alpine
        mem_limit: 128m
        depends_on:
            - alfresco
            - solr6
            - share
            - content-app
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf  # modified nginx.conf
            - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd  # modified nginx.htpasswd
            - /certs/cert-current.pem:/etc/nginx/localhost.cer # use my server‘s certificate
            - /certs/key-current.pem:/etc/nginx/localhost.key  # use my server’s key
        ports:
            - 443:443
```
`nginx.conf`

```nginx
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    server {

        listen *:443 ssl;
        ssl_certificate     /etc/nginx/localhost.cer;
        ssl_certificate_key /etc/nginx/localhost.key;
        ssl_ciphers         EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
        ssl_protocols       TLSv1.1 TLSv1.2;


        client_max_body_size 0;

        set  $allowOriginSite *;
        proxy_pass_request_headers on;
        proxy_pass_header Set-Cookie;

        # Increment timeout values
        proxy_connect_timeout 600;
        proxy_send_timeout    600;
        proxy_read_timeout    600;
        send_timeout          600;

        # External settings, do not remove
        #ENV_ACCESS_LOG

        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host            $host:$server_port;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass_header Set-Cookie;

        # Protect access to SOLR APIs
        location ~ ^(/.*/service/api/solr/.*)$ {return 403;}
        location ~ ^(/.*/s/api/solr/.*)$ {return 403;}
        location ~ ^(/.*/wcservice/api/solr/.*)$ {return 403;}
        location ~ ^(/.*/wcs/api/solr/.*)$ {return 403;}
        location ~ ^(/.*/proxy/alfresco/api/solr/.*)$ {return 403 ;}
        location ~ ^(/.*/-default-/proxy/alfresco/api/.*)$ {return 403;}


        # Alfresco Content Application Proxy
        #ACA_ENDPOINT
        location / {
          # added redirect to share
          rewrite ^/$ /share;
        }

        # Repository Proxy
        location /alfresco/ {
          proxy_pass http://alfresco:8080;
        }

        # Api-Explorer Proxy
        location /api-explorer/ {
          proxy_pass http://alfresco:8080;
        }

        # Share Proxy
        location /share/ {
          proxy_pass http://share:8080;
        }

        # SOLR Proxy
        location /solr/ {
          proxy_pass http://solr6:8983;
          auth_basic "Solr web console";
          auth_basic_user_file /etc/nginx/conf.d/nginx.htpasswd;
        }

    }
}
```

modified `nginx.htpasswd` to have admin:admin password (but of course you should change it to your needs with command line tool `htpasswd`, in this example `admin` would be the password, e.g. for solr interface):
```htpasswd
admin:$apr1$94LKbA3l$fawCs80fVfXNG.IMlazEl1
```
